"""Alembic migration environment for HYPERPLM.

Target metadata is the SQLAlchemy Core schema in app/db.py. The connection URL
comes from DATABASE_URL (see app.db.database_url) — never hardcoded here.

Note (Phase 2 §12.3): Alembic autogenerate does NOT detect row-level security
policies, FORCE ROW LEVEL SECURITY, or WITH CHECK clauses. All RLS/policy DDL must
be hand-authored via op.execute(...) in the migrations, not autogenerated.
"""
from __future__ import annotations

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make the app package importable when Alembic runs from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db import database_url, metadata  # noqa: E402

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Inject the runtime URL (env-driven) into the Alembic config.
config.set_main_option("sqlalchemy.url", database_url())

target_metadata = metadata


def run_migrations_offline() -> None:
    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
