"""initial schema - port of the single-tenant PLM schema to PostgreSQL

Phase 2, step 1. Creates the baseline tables (roles, users, parts, part_attributes,
part_revisions, part_relationships, documents, file_versions, audit_log) on
PostgreSQL. These mirror app/db.py (the SQLAlchemy Core source of truth); Alembic
migrations are the point-in-time change log, so the DDL is spelled out explicitly
here (renders in both online and offline --sql modes, and is independently reviewable).

No tenancy yet: organizations, org_id columns, and row-level security are added in
step 2 (a later, hand-authored migration — RLS DDL is never autogenerated, per §12.3).
Secondary/filter indexes are intentionally deferred to step 2, where they become
composite (org_id, ...) indexes — creating single-column versions now would only be
replaced.

Revision ID: 0001
Revises:
Create Date: 2026-07-21
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _pk() -> sa.Column:
    return sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True)


def _created() -> sa.Column:
    return sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now())


def upgrade() -> None:
    op.create_table(
        "roles",
        _pk(),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("can_release", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("can_view", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("can_write", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("can_upload", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("can_checkout", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("can_admin", sa.Integer, nullable=False, server_default=sa.text("0")),
        _created(),
        sa.UniqueConstraint("name", name="uq_roles_name"),
    )

    op.create_table(
        "users",
        _pk(),
        sa.Column("username", sa.Text, nullable=False),
        sa.Column("email", sa.Text),
        sa.Column("password_hash", sa.Text),
        sa.Column("role_id", sa.BigInteger,
                  sa.ForeignKey("roles.id", ondelete="SET NULL", name="fk_users_role_id_roles")),
        sa.Column("is_active", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("must_change_password", sa.Integer, nullable=False, server_default=sa.text("0")),
        _created(),
        sa.Column("last_active", sa.TIMESTAMP(timezone=True)),
        sa.UniqueConstraint("username", name="uq_users_username"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    op.create_table(
        "parts",
        _pk(),
        sa.Column("part_number", sa.Text, nullable=False),
        sa.Column("part_name", sa.Text, nullable=False),
        sa.Column("part_revision", sa.Text, nullable=False, server_default=sa.text("'A'")),
        sa.Column("description", sa.Text),
        sa.Column("part_level", sa.Text),
        sa.Column("release_status", sa.Text, nullable=False, server_default=sa.text("'Prototype'")),
        sa.Column("checked_out_by", sa.BigInteger,
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_parts_checked_out_by_users")),
        sa.Column("checked_out_at", sa.TIMESTAMP(timezone=True)),
        sa.Column("checked_out_station", sa.Text),
        sa.Column("created_by", sa.BigInteger,
                  sa.ForeignKey("users.id", name="fk_parts_created_by_users"), nullable=False),
        _created(),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.Column("is_locked", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.UniqueConstraint("part_number", name="uq_parts_part_number"),
    )

    op.create_table(
        "part_attributes",
        _pk(),
        sa.Column("part_id", sa.BigInteger,
                  sa.ForeignKey("parts.id", ondelete="CASCADE", name="fk_part_attributes_part_id_parts"),
                  nullable=False),
        sa.Column("attr_key", sa.Text, nullable=False),
        sa.Column("attr_value", sa.Text),
        sa.Column("attr_order", sa.Integer, nullable=False, server_default=sa.text("0")),
        _created(),
        sa.UniqueConstraint("part_id", "attr_key", name="uq_part_attributes_part_id_attr_key"),
    )

    op.create_table(
        "part_revisions",
        _pk(),
        sa.Column("part_id", sa.BigInteger,
                  sa.ForeignKey("parts.id", ondelete="CASCADE", name="fk_part_revisions_part_id_parts"),
                  nullable=False),
        sa.Column("revision_label", sa.Text, nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("changed_by", sa.BigInteger,
                  sa.ForeignKey("users.id", name="fk_part_revisions_changed_by_users"), nullable=False),
        sa.Column("changed_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.Column("snapshot_json", sa.Text),
    )

    op.create_table(
        "part_relationships",
        _pk(),
        sa.Column("parent_part_id", sa.BigInteger,
                  sa.ForeignKey("parts.id", ondelete="CASCADE", name="fk_part_relationships_parent_part_id_parts"),
                  nullable=False),
        sa.Column("child_part_id", sa.BigInteger,
                  sa.ForeignKey("parts.id", ondelete="CASCADE", name="fk_part_relationships_child_part_id_parts"),
                  nullable=False),
        sa.Column("quantity", sa.Float, nullable=False, server_default=sa.text("1.0")),
        sa.Column("relationship_type", sa.Text, nullable=False, server_default=sa.text("'assembly'")),
        sa.Column("notes", sa.Text),
        _created(),
        sa.UniqueConstraint("parent_part_id", "child_part_id", name="uq_part_relationships_parent_child"),
    )

    op.create_table(
        "documents",
        _pk(),
        sa.Column("part_id", sa.BigInteger,
                  sa.ForeignKey("parts.id", ondelete="SET NULL", name="fk_documents_part_id_parts")),
        sa.Column("filename", sa.Text, nullable=False),
        sa.Column("stored_path", sa.Text, nullable=False),
        sa.Column("file_type", sa.Text, nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("uploaded_by", sa.BigInteger,
                  sa.ForeignKey("users.id", name="fk_documents_uploaded_by_users"), nullable=False),
        sa.Column("uploaded_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "file_versions",
        _pk(),
        sa.Column("document_id", sa.BigInteger,
                  sa.ForeignKey("documents.id", ondelete="CASCADE", name="fk_file_versions_document_id_documents"),
                  nullable=False),
        sa.Column("version_label", sa.Text, nullable=False),
        sa.Column("backup_path", sa.Text, nullable=False),
        sa.Column("file_size", sa.BigInteger),
        sa.Column("saved_by", sa.BigInteger,
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_file_versions_saved_by_users")),
        sa.Column("saved_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.Column("is_current", sa.Integer, nullable=False, server_default=sa.text("0")),
    )

    op.create_table(
        "audit_log",
        _pk(),
        sa.Column("user_id", sa.BigInteger,
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_audit_log_user_id_users")),
        sa.Column("action", sa.Text, nullable=False),
        sa.Column("entity_type", sa.Text, nullable=False),
        sa.Column("entity_id", sa.BigInteger),
        sa.Column("detail_json", sa.Text),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    for table in (
        "audit_log", "file_versions", "documents", "part_relationships",
        "part_revisions", "part_attributes", "parts", "users", "roles",
    ):
        op.drop_table(table)
