"""tenancy + row-level security

Phase 2, step 2. Introduces organizations and org_members, moves role off users
(role is now per-membership), makes roles per-org, adds org_id to every data table,
and enforces tenant isolation with PostgreSQL row-level security.

All RLS/policy/role/grant DDL is hand-authored here (Alembic autogenerate cannot see
it — §12.3). Tables are empty at this revision (0001 created them fresh), so org_id is
added NOT NULL without backfill.

Isolation model:
- Every tenant table gets `org_id` and an RLS policy keyed on the `app.current_org`
  GUC, which the app sets per request (SET LOCAL). Policy uses the bare
  current_setting(...) form, so a query outside a scoped transaction ERRORS rather
  than leaking rows (fail closed loud, §12.4).
- FORCE ROW LEVEL SECURITY makes the policy apply even to the table owner.
- The app connects as `hyperplm_app`, a NON-superuser role, because superusers bypass
  RLS entirely. The migration/owner role (superuser) is used only for migrations/admin.
- organizations / org_members / users are global (no RLS): membership is resolved by
  user_id BEFORE an active org exists (§12.2), so it must not sit behind the tenant GUC.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-25
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Self-contained (migrations must not import evolving app code).
TENANT_TABLES = (
    "roles", "parts", "part_attributes", "part_revisions",
    "part_relationships", "documents", "file_versions", "audit_log",
)


def upgrade() -> None:
    # ── Organizations (global) ────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE organizations (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
            name          TEXT NOT NULL,
            slug          TEXT NOT NULL,
            owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            created_at    TIMESTAMPTZ DEFAULT now(),
            CONSTRAINT pk_organizations PRIMARY KEY (id),
            CONSTRAINT uq_organizations_slug UNIQUE (slug)
        )
    """)

    # ── Users: platform-admin flag, drop per-user role ────────────────────────
    # is_platform_admin marks the capability only; the RLS-bypass path is NOT
    # wired until Phase 3 (§12.5).
    op.execute("ALTER TABLE users ADD COLUMN is_platform_admin INTEGER NOT NULL DEFAULT 0")
    op.execute("ALTER TABLE users DROP COLUMN role_id")

    # ── Org membership (global lookup path, §12.2) ────────────────────────────
    op.execute("""
        CREATE TABLE org_members (
            id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
            org_id     BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role_id    BIGINT REFERENCES roles(id) ON DELETE SET NULL,
            created_at TIMESTAMPTZ DEFAULT now(),
            CONSTRAINT pk_org_members PRIMARY KEY (id),
            CONSTRAINT uq_org_members_org_user UNIQUE (org_id, user_id)
        )
    """)
    op.execute("CREATE INDEX ix_org_members_user_id ON org_members (user_id)")

    # ── Add org_id to every tenant table (empty tables → NOT NULL is safe) ─────
    for t in TENANT_TABLES:
        op.execute(
            f"ALTER TABLE {t} ADD COLUMN org_id BIGINT NOT NULL "
            f"REFERENCES organizations(id) ON DELETE CASCADE"
        )

    # ── Per-org uniqueness (replaces the old global uniques) ──────────────────
    op.execute("ALTER TABLE roles DROP CONSTRAINT uq_roles_name")
    op.execute("ALTER TABLE roles ADD CONSTRAINT uq_roles_org_name UNIQUE (org_id, name)")
    op.execute("ALTER TABLE parts DROP CONSTRAINT uq_parts_part_number")
    op.execute("ALTER TABLE parts ADD CONSTRAINT uq_parts_org_part_number UNIQUE (org_id, part_number)")

    # ── Org-scoped / filter indexes ───────────────────────────────────────────
    op.execute("CREATE INDEX ix_parts_org_release_status ON parts (org_id, release_status)")
    op.execute("CREATE INDEX ix_parts_org_created_by ON parts (org_id, created_by)")
    op.execute("CREATE INDEX ix_parts_checked_out_by ON parts (checked_out_by)")
    op.execute("CREATE INDEX ix_part_attributes_part_id ON part_attributes (part_id)")
    op.execute("CREATE INDEX ix_part_revisions_part_id ON part_revisions (part_id)")
    op.execute("CREATE INDEX ix_part_relationships_parent ON part_relationships (parent_part_id)")
    op.execute("CREATE INDEX ix_part_relationships_child ON part_relationships (child_part_id)")
    op.execute("CREATE INDEX ix_documents_part_id ON documents (part_id)")
    op.execute("CREATE INDEX ix_file_versions_document_id ON file_versions (document_id)")
    op.execute("CREATE INDEX ix_audit_log_org_time ON audit_log (org_id, timestamp)")
    op.execute("CREATE INDEX ix_audit_log_entity ON audit_log (org_id, entity_type, entity_id)")

    # ── Row-level security: enable + force + isolation policy on each table ────
    for t in TENANT_TABLES:
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {t}_tenant_isolation ON {t}
              USING      (org_id = current_setting('app.current_org')::bigint)
              WITH CHECK (org_id = current_setting('app.current_org')::bigint)
        """)

    # ── Application role (non-superuser → RLS applies) ────────────────────────
    # LOGIN with no password here; the password is set server-side (never committed)
    # when the app is wired to Postgres in step 4.
    op.execute("""
        DO $$ BEGIN
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'hyperplm_app') THEN
            CREATE ROLE hyperplm_app LOGIN;
          END IF;
        END $$;
    """)
    op.execute("GRANT USAGE ON SCHEMA public TO hyperplm_app")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO hyperplm_app")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO hyperplm_app")
    # The app has no business touching migration bookkeeping.
    op.execute("REVOKE ALL ON alembic_version FROM hyperplm_app")
    # Future tables/sequences (later migrations, created by the owner) auto-grant.
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA public "
               "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hyperplm_app")
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA public "
               "GRANT USAGE, SELECT ON SEQUENCES TO hyperplm_app")


def downgrade() -> None:
    # Revoke app-role access and drop the role.
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA public "
               "REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM hyperplm_app")
    op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA public "
               "REVOKE USAGE, SELECT ON SEQUENCES FROM hyperplm_app")
    op.execute("DROP OWNED BY hyperplm_app")
    op.execute("DROP ROLE IF EXISTS hyperplm_app")

    # Drop RLS policies and disable RLS.
    for t in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}")
        op.execute(f"ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} DISABLE ROW LEVEL SECURITY")

    # Drop org-scoped indexes.
    for ix in (
        "ix_parts_org_release_status", "ix_parts_org_created_by", "ix_parts_checked_out_by",
        "ix_part_attributes_part_id", "ix_part_revisions_part_id",
        "ix_part_relationships_parent", "ix_part_relationships_child",
        "ix_documents_part_id", "ix_file_versions_document_id",
        "ix_audit_log_org_time", "ix_audit_log_entity",
    ):
        op.execute(f"DROP INDEX IF EXISTS {ix}")

    # Restore global uniqueness.
    op.execute("ALTER TABLE parts DROP CONSTRAINT uq_parts_org_part_number")
    op.execute("ALTER TABLE parts ADD CONSTRAINT uq_parts_part_number UNIQUE (part_number)")
    op.execute("ALTER TABLE roles DROP CONSTRAINT uq_roles_org_name")
    op.execute("ALTER TABLE roles ADD CONSTRAINT uq_roles_name UNIQUE (name)")

    # Drop org_id from tenant tables.
    for t in TENANT_TABLES:
        op.execute(f"ALTER TABLE {t} DROP COLUMN org_id")

    # Drop membership + org tables, restore users.role_id.
    op.execute("DROP INDEX IF EXISTS ix_org_members_user_id")
    op.execute("DROP TABLE org_members")
    op.execute("ALTER TABLE users DROP COLUMN is_platform_admin")
    op.execute("ALTER TABLE users ADD COLUMN role_id BIGINT "
               "REFERENCES roles(id) ON DELETE SET NULL")
    op.execute("DROP TABLE organizations")
