"""public team directory — the global lookup that makes the fan layer possible

Phase 3, step 3. Fans are anonymous: they have no active org, so they cannot read
`teams` (a tenant table whose RLS policy keys on the app.current_org GUC and fails
closed). A public team page therefore needs a GLOBAL lookup to answer "which org
owns this team?" before a tenant session can be opened.

`team_directory` is that lookup, and nothing more: the minimal public identity of a
team plus its org_id. It carries no engineering data. The flow is:

    anonymous request -> team_directory (global, no RLS) -> org_id
        -> tenant_session(org_id)  [RLS scopes to exactly that tenant]
        -> read rows WHERE visibility = 'public'

So RLS still guarantees cross-tenant isolation on every read, and the visibility
column still guarantees the fan wall inside the tenant. A team only appears to the
public when `is_public` is true — private by default, opt-in to publish.

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-22
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE team_directory (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
            team_id     BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
            org_id      BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            slug        TEXT NOT NULL,
            name        TEXT NOT NULL,
            car_number  TEXT NOT NULL DEFAULT '',
            series      TEXT NOT NULL DEFAULT '',
            class       TEXT NOT NULL DEFAULT '',
            is_public   INTEGER NOT NULL DEFAULT 0,
            updated_at  TIMESTAMPTZ DEFAULT now(),
            CONSTRAINT pk_team_directory PRIMARY KEY (id),
            CONSTRAINT uq_team_directory_team_id UNIQUE (team_id),
            CONSTRAINT uq_team_directory_slug UNIQUE (slug)
        )
    """)
    op.execute("CREATE INDEX ix_team_directory_public ON team_directory (is_public)")

    # Backfill any teams that already exist. Published by default in this first
    # cut so an existing tenant's teams are visible to fans immediately; teams can
    # be unpublished per row. (Reviewers: flip to 0 here if opt-in is preferred.)
    op.execute("""
        INSERT INTO team_directory (team_id, org_id, slug, name, car_number, series, class, is_public)
        SELECT t.id, t.org_id,
               lower(regexp_replace(t.name || '-' || t.car_number, '[^a-zA-Z0-9]+', '-', 'g')),
               t.name, t.car_number, t.series, t.class, 1
        FROM teams t
        ON CONFLICT (team_id) DO NOTHING
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_team_directory_public")
    op.execute("DROP TABLE IF EXISTS team_directory")
