"""race series + setup templates

Phase 3, step 7. Two gaps raised in testing:

1. "when we create sessions and log laps could teams select Series and Event
   Name, and import the calendar?"  Series were free text on `teams` and events
   were ad-hoc strings, so nothing could be selected or reused. `series` is now
   a reference table, and an event can point at the series it belongs to.

   The calendar itself is deliberately NOT invented here. Circuits already carry
   a `series_tag`, so choosing a series narrows the track list to the ones that
   series actually visits — real information we hold. Importing dated rounds
   needs a real feed; `series.calendar_source` is where that provenance will go
   so nobody has to guess whether a date was imported or typed.

2. "teams need to make their own templates — IndyCar will be different to IMSA."
   A setup sheet was a bare key/value list, so every sheet started from nothing
   and two engineers on the same team would name fields differently. Templates
   are per-org (tenant-scoped, RLS like everything else) and optionally tied to a
   series, so a GT3 template and an IndyCar template can coexist.

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-31
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Real championships. No invented rounds or dates.
SERIES = [
    ("imsa-wtsc", "IMSA WeatherTech SportsCar Championship", "IMSA", "sports car"),
    ("imsa-vp", "IMSA VP Racing SportsCar Challenge", "IMSA", "sports car"),
    ("indycar", "NTT IndyCar Series", "IndyCar", "open wheel"),
    ("indy-nxt", "Indy NXT by Firestone", "IndyCar", "open wheel"),
]


def upgrade() -> None:
    # ── series: global reference data, read with no org context ──────────────
    op.execute("""
        CREATE TABLE series (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
            series_id       TEXT NOT NULL,
            name            TEXT NOT NULL,
            track_tag       TEXT NOT NULL DEFAULT '',
            discipline      TEXT NOT NULL DEFAULT '',
            calendar_source TEXT,
            created_at      TIMESTAMPTZ DEFAULT now(),
            CONSTRAINT pk_series PRIMARY KEY (id),
            CONSTRAINT uq_series_series_id UNIQUE (series_id)
        )
    """)
    rows = ", ".join(
        "('{}', '{}', '{}', '{}')".format(*[v.replace("'", "''") for v in s])
        for s in SERIES)
    op.execute("INSERT INTO series (series_id, name, track_tag, discipline) "
               f"VALUES {rows} ON CONFLICT (series_id) DO NOTHING")

    # an event can belong to a series (optional — private tests need no series)
    op.execute("ALTER TABLE events ADD COLUMN series_id BIGINT REFERENCES series(id)")
    op.execute("CREATE INDEX ix_events_series ON events (series_id)")

    # ── setup templates: per-org, so a team owns its own field lists ─────────
    op.execute("""
        CREATE TABLE setup_templates (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
            org_id      BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            name        TEXT NOT NULL,
            series_id   BIGINT REFERENCES series(id),
            description TEXT NOT NULL DEFAULT '',
            created_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
            created_at  TIMESTAMPTZ DEFAULT now(),
            CONSTRAINT pk_setup_templates PRIMARY KEY (id),
            CONSTRAINT uq_setup_templates_org_name UNIQUE (org_id, name)
        )
    """)
    op.execute("""
        CREATE TABLE setup_template_fields (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
            org_id      BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            template_id BIGINT NOT NULL REFERENCES setup_templates(id) ON DELETE CASCADE,
            group_name  TEXT NOT NULL DEFAULT '',
            attr_key    TEXT NOT NULL,
            unit        TEXT NOT NULL DEFAULT '',
            default_value TEXT NOT NULL DEFAULT '',
            field_order INTEGER NOT NULL DEFAULT 0,
            CONSTRAINT pk_setup_template_fields PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX ix_setup_template_fields_template "
               "ON setup_template_fields (template_id)")
    op.execute("CREATE INDEX ix_setup_templates_org ON setup_templates (org_id)")

    # record which template a sheet came from
    op.execute("ALTER TABLE setups ADD COLUMN template_id BIGINT "
               "REFERENCES setup_templates(id) ON DELETE SET NULL")

    # RLS, same contract as every other tenant table
    for t in ("setup_templates", "setup_template_fields"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {t}_tenant_isolation ON {t}
              USING      (org_id = current_setting('app.current_org')::bigint)
              WITH CHECK (org_id = current_setting('app.current_org')::bigint)
        """)
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON series, setup_templates, "
               "setup_template_fields TO hyperplm_app")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO hyperplm_app")


def downgrade() -> None:
    for t in ("setup_template_fields", "setup_templates"):
        op.execute(f"DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}")
    op.execute("ALTER TABLE setups DROP COLUMN IF EXISTS template_id")
    op.execute("DROP TABLE IF EXISTS setup_template_fields")
    op.execute("DROP TABLE IF EXISTS setup_templates")
    op.execute("DROP INDEX IF EXISTS ix_events_series")
    op.execute("ALTER TABLE events DROP COLUMN IF EXISTS series_id")
    op.execute("DROP TABLE IF EXISTS series")
